/**
 * TRANSLATION
 */
export const DETECH_LANGUAGE           = 'DETECH_LANGUAGE'
export const FETCH_TRANSLATION         = 'FETCH_TRANSLATION'
export const FETCH_TRANSLATION_SUCCESS = 'FETCH_TRANSLATION_SUCCESS'
export const FETCH_TRANSLATION_ERROR   = 'FETCH_TRANSLATION_ERROR'
export const SWITCH_LANGUAGE           = 'SWITCH_LANGUAGE'
export const SWITCH_LANGUAGE_SUCCESS   = 'SWITCH_LANGUAGE_SUCCESS'
