export const FETCH_LANGUAGES      = 'FETCH_LANGUAGES'
export const FETCH_LANGUAGES_DONE = 'FETCH_LANGUAGES_DONE'
export const SWITCH_LANGUAGE      = 'SWITCH_LANGUAGE'
export const DETECH_LANGUAGE      = 'DETECH_LANGUAGE'
